{
    "name": "Hospital Management",
    "version": "19.0.1.0.0",
    "category": "Hospital",
    "summary": "Comprehensive hospital management system",
    "author": "Evgen Cerkun",
    "license": "LGPL-3",
    "depends": [
                "base",
                "hr",
                ],
    "data": [
        "security/ir.model.access.csv",
        "wizard/hr_hospital_disease_report_template.xml",
        "report/hr_hospital_report_actions.xml",
        "report/hr_hospital_doctor_report_paperformat.xml",
        "report/hr_hospital_doctor_report_actions.xml",
        "report/hr_hospital_doctor_report_template.xml",
        "wizard/hr_hospital_disease_report_wizard_views.xml",
        "wizard/hr_hospital_disease_month_report_wizard_views.xml",
        "wizard/mass_reassign_doctor_wizard_views.xml",
        "wizard/visit_report_wizard_views.xml",
        "views/hr_hospital_visit_views.xml",
        "views/hr_hospital_doctor_views.xml",
        "views/hr_hospital_patient_views.xml",
        "views/hr_hospital_disease_views.xml",
        "views/hr_hospital_doctor_category_views.xml",
        "views/hr_hospital_doctor_history_views.xml",
        "views/hr_hospital_dashboard_views.xml",
        "views/hr_hospital_menus.xml",
    ],
    "demo": [
        "demo/hr_hospital_disease_demo.xml",
        "demo/hr_hospital_doctor_category_demo.xml",
        "demo/hr_hospital_doctor_demo.xml",
        "demo/hr_hospital_patient_demo.xml",
        "demo/hr_hospital_visit_demo.xml",
        "demo/hr_doctor_history_demo.xml",
    ],
    "installable": True,
    "application": True,
    "images": ["static/description/icon.png"],
    "assets": {
        "web.assets_backend": [
            "hr_hospital/static/src/scss/hr_hospital_kanban.scss",
        ]
    },
}
